language: crystal
dist: trusty
sudo: required
services:
  - postgresql
  - mysql
addons:
  postgresql: 9.4
env:
  - DB=mysql DB_USER=root DB_PASSWORD=""
  - DB=postgres DB_USER=postgres DB_PASSWORD=""
before_script:
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database jennifer_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then bash .travis.install-mysql-5.7.sh; crystal ./examples/run.cr -- db:create; fi"
  - crystal ./examples/run.cr -- db:migrate
